### ISSUE TITLE
Missing dataset in /examples/synthetic/example_sweep

### ISSUE THREAD

**Issue by DelinQu** [ThomasZiegler/RS-aware-differential-SfM#1]
Hi ThomasZiegler,
There is a slight problem in /examples/synthetic/example_sweep:
- There are the following Tasks in the task file:
`
test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=0_gamma=0.8
test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=0.25_gamma=0.8
test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=0.5_gamma=0.8
test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=0.75_gamma=0.8
test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=1_gamma=0.8
test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=1.25_gamma=0.8
`
- However, there are only the following data sets in the directory:
`
├── test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=0.25_gamma=0.8
├── test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=0.75_gamma=0.8
└── test__v=[0.03;0.03;0]_w=[0;0;0.5]_k=1.25_gamma=0.8
`
Therefore, the `error: (-215:Assertion failed) !fixedSize() in function 'release'`  may occur when running the code.

**Comment by ThomasZiegler** [comment]
Hi DelinQu

You're right the data for `k=0, k=0.5, k=1.0` are missing. It seems we removed them in order to fulfill the strict file size limit of 100MB for the `example_sweep.tar.gz` file. Since it's almost 3 years since we did this project I no longer have the raw data on my computer. However, you should be able to generate any desired values with the MATLAB tool in `/matlab_synthetic_data`. 

In any case thank you pointing this out and I will update the README and task.txt file.
